name: Deploy Using NPM

on:
  push:
    branches:
    - main
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu-latest']

    steps:
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}